[project]
name = "protected-fishing-areas"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=2.7.0",
    "pandas",
    "sqlalchemy",
    "psycopg2-binary",
    "dbt-postgres>=1.10.0",
]
